### ISSUE TITLE
Can't find constructor of classes nested in objects (scala 2)

### ISSUE THREAD

**Issue by coreywoodfield** [yakivy/jam#1]
```
object A {
  class B()
}
trait Module {
  val b: A.B = jam.brew[A.B]
}
```
Expected: This works
Actual: `Unable to find public constructor for (A.B)`

**Comment by yakivy** [comment]
Wow, what an unusual activity here :flushed:
@coreywoodfield  Try `0.0.6.0-SNAPSHOT` version, it should brew nested classes.

**Comment by yakivy** [comment]
Resolved, feel free to reopen if you will face it again.
