### ISSUE TITLE
Can't handle type parameters (scala 2)

### ISSUE THREAD

**Issue by coreywoodfield** [yakivy/jam#2]
```
class A[B]()
trait Module {
  val a: A[String] = jam.brew[A[String]]
}
```
Expected: This works
Actual: `Unable to find public constructor for (B[String])`

Related:
```
class A[B](b: B)
trait Module {
  val string: String = ""
  val a: A[String] = jam.brew[A[String]]
}
```
Expected: This works
Actual: `Unable to find public constructor for (B[String])`

**Comment by yakivy** [comment]
Resolved in `0.0.6`, feel free to reopen if you will face it again.
