### ISSUE TITLE
Doesn't inject non-implicit parameters that are implicit fields (scala 2)

### ISSUE THREAD

**Issue by coreywoodfield** [yakivy/jam#3]
```
class A(b: Long, implicit val c: Int)
trait Module {
  val b: Long = ???
  val c: Int = ???
  val a: A = jam.brew[A]
}
```
Note that `c` here is in the normal parameter list, so must be provided normally to the class when constructed, but is used as an implicit field inside the class. This is effectively equivalent to
```
class A(b: String, _c: Int) {
  implicit val c: Int = _c
}
```

Expected: This works
Actual: `Unable to resolve implicit instance for (A).c`

**Comment by yakivy** [comment]
Em... I did the fix, but it turned out that it is not possible to check if the arg list is implicit in scala 2 macros :confused:, so I'm just checking if the first argument in the list is implicit. I hope it will cover all your cases: `0.0.10`

**Comment by coreywoodfield** [comment]
I believe it will, thanks!
