### ISSUE TITLE
Can't inject Strings (scala 2)

### ISSUE THREAD

**Issue by coreywoodfield** [yakivy/jam#5]
```
class A(b: String)
trait Module {
  val string: String = ""
  val a: A = jam.brew[A]
}
```
Expected: This works
Actual: `More than one injection candidate was found for (A).b`

I added `parameterCandidates` to this error message locally (note: This may be useful in general as it makes debugging this error much easier) and saw that it had `List((value string,String("")), (method toString,(): String))`. The `toString` method probably shouldn't be considered a candidate for injection

**Comment by yakivy** [comment]
Resolved in `0.0.7`, feel free to reopen if you will face it again.
