### ISSUE TITLE
[Feature request] Allow values of type B to be injected for constructor args of type A if B <: A

### ISSUE THREAD

**Issue by denvercoder10** [yakivy/jam#8]
It would be nice to be able to automatically inject values of a subclass type for constructor args that are of the superclass type.

Here's a minimal example:
```scala
class A()
class B extends A()
class C(a: A)

trait TestModule {
  // would be nice if this is all we needed to provide an A
  val b: B = jam.brew[B]
  // If the following line is uncommented, compilation works, since we have an A in scope
  // val a: A = b
  val c: C = jam.brew[C]
}
```

**Comment by yakivy** [comment]
@denvercoder10 try `0.0.11`, it should work there (https://github.com/yakivy/jam/commit/b1c7ae726161c11e547d944e701855715c3bfa23)
